config/routes.rb
Photohub::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :pictures,        only: [:edit, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]

  resources :albums,          only: [:show, :create, :destroy] do
    resources :pictures,        only: [:new, :create]
    member do
      post 'invite/:user_id', action: 'invite',         as: 'invite_to'
      post 'revoke/:user_id', action: 'revoke',         as: 'revoke_from'
      get  'collaborators',   action: 'collaborators',  as: 'collaborators'
      get  'invitations',     action: 'invitations',    as: 'invitations'
    end
  end

  resources :collaborations,  only: [:index] do
    collection do
      get   'pending',  action: 'pending',  as: 'pending'
    end
    member do
      post  'accept',   action: 'accept',   as: 'accept'
      post  'reject',   action: 'reject',   as: 'reject'
    end
  end

  root to: "static_pages#home"

  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  match "/help", to: "static_pages#help"
  match "/contact", to: "static_pages#contact"

end

app/views/shared/_actions_picture.html.haml
- if current_user?(object.user)
  = link_to "edit", edit_picture_path(object)
  = link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.name

app/views/shared/_album_form.html.haml
= form_for(@album) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_field :title, placeholder: "New album title..."
  .field
    = f.text_area :description, placeholder: "Something to say?"
  = f.submit "New Album", class: "btn btn-large btn-primary"

app/views/shared/_anonymous_home.html.haml
.hero-unit.center
  %h1= "Welcome to PhotoHub"
  %h2
    This is the home page for
    %a{ :href => '/' }= "PhotoHub"
    while it's under construction...

  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"

= link_to image_tag("rails.png", alt: "rails"), "http://rubyonrails.org/"

app/views/shared/_delete_album.html.haml
- if current_user?(object.user)
  = link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.title

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}
    %ul
      - object.errors.full_messages.each do |msg|
        %li= "* #{msg}"

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.albums
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{ id: feed_item.id }
  = link_to gravatar_for(feed_item.user, size: 30), feed_item.user
  %span.user
    = link_to feed_item.user.name, feed_item.user
  %span.content
    = wrap(feed_item.title)
  %span.content
    = wrap(feed_item.description)
  %span.timestamp
    Created #{ time_ago_in_words(feed_item.created_at) } ago.
  = render 'shared/delete_album', object: feed_item

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{ href: following_user_path(@user) }
    %strong#following.stat= @user.followed_users.count
    following
  %a{ href: followers_user_path(@user) }
    %strong#followers.stat= @user.followers.count
    followers

app/views/shared/_user_home.html.haml
.row
  %aside.span4
    %section
      = render 'shared/user_info'
    %section
      = render 'shared/stats'
    %section
      = render 'shared/album_form'
  .span8
    %h3= "Album Feed"
    = render 'shared/feed'

app/views/shared/_user_info.html.haml
%a{ href: user_path(current_user) }
  = gravatar_for current_user, size: 52

%h1
  = current_user.name
%span
  = link_to "view my profile", current_user
%span.count
  = pluralize(current_user.albums.count, "album")