config/routes.rb
Photohub::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :pictures,        only: [:edit, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]

  resources :albums,          only: [:show, :create, :destroy] do
    resources :pictures,        only: [:new, :create]
    member do
      post 'invite/:user_id', action: 'invite',         as: 'invite_to'
      post 'revoke/:user_id', action: 'revoke',         as: 'revoke_from'
      get  'collaborators',   action: 'collaborators',  as: 'collaborators'
      get  'invitations',     action: 'invitations',    as: 'invitations'
    end
  end

  resources :collaborations,  only: [:index] do
    collection do
      get   'pending',  action: 'pending',  as: 'pending'
    end
    member do
      post  'accept',   action: 'accept',   as: 'accept'
      post  'reject',   action: 'reject',   as: 'reject'
    end
  end

  root to: "static_pages#home"

  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  match "/help", to: "static_pages#help"
  match "/contact", to: "static_pages#contact"

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :title, :description
  belongs_to :user
  has_many :pictures, dependent: :destroy

  has_many :collaborations, dependent: :destroy
  has_many :collaborators, through: :collaborations, source: :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true

  default_scope order: 'albums.created_at DESC'

  def collaborating?(other_user)
    Collaboration.find_by_user_id_and_status(other_user.id, Collaboration::ACCEPTED_STATUS)
  end

  def invited?(other_user)
    Collaboration.find_by_user_id_and_status(other_user.id, Collaboration::PENDING_STATUS)
  end

  def invite!(other_user)
    collaborations.create!(user_id: other_user.id,
              role: Collaboration::COLLABORATOR_ROLE,
              status: Collaboration::PENDING_STATUS) if other_user != user
  end

  def revoke!(other_user)
    collaborations.find_by_user_id(other_user.id).destroy
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :signed_in_user,  except: [:show]
  before_filter :correct_user,    only: [:destroy, :invite, :revoke]
  before_filter :allowed_user,    only: [:collaborators, :invitations]

  def show
    @user = current_user
    @album = Album.find_by_id(params[:id])
  end

  def create
    @album = current_user.albums.build(params[:album])
    if @album.save
      flash[:success] = "Album created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @album.destroy
    redirect_to root_url
  end

  def invite
    if current_user == params[:user_id]
      flash[:error] = "Owner can't be invited to the album"
      redirect_to root_url
    end

    @user = User.find_by_id(params[:user_id])
    @album.invite!(@user)
    redirect_to @album
  end

  def revoke
    @user = User.find_by_id(params[:user_id])
    @album.revoke!(@user)
    redirect_to @album
  end

  def collaborators
    @collaborators = @album.collaborators.where(collaborations: {status: Collaboration::ACCEPTED_STATUS})
  end

  def invitations
    @invited_users = @album.collaborators.where(collaborations: {status: Collaboration::PENDING_STATUS})
  end

  private

    def correct_user
      @album = current_user.albums.find_by_id!(params[:id])
    rescue
      redirect_to root_url
    end

    def allowed_user
      @album = current_user.albums.find_by_id(params[:id])
      @album = current_user.collaborating_albums.find_by_id(params[:id]) unless @album
      redirect_to root_url unless @album
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
    end
end

app/views/albums/_album.html.haml
%li
  = link_to wrap(album.title), album_path(album), class: "content"
  %span.timestamp
    Created #{ time_ago_in_words(album.created_at) } ago.
  = render 'shared/delete_album', object: album

app/views/albums/_collaboration_item.html.haml
%li
  album.title

app/views/albums/_collaborations.html.haml
- if albums.any?
  %h2
    Collaborations
    %small= "(#{albums.count})"
  %ul.collaborations
    = render partial: 'album/collaboration_item', collection: albums

app/views/albums/_invitation_item.html.haml
%li
  invitation.title

app/views/albums/_invitations.html.haml
- if invitations.any?
  %h2
    Invitations
    %small= "(#{invitations.count})"
  %ul.invitations
    = render partial: 'album/invitation_item', collection: invitations

app/views/albums/collaborators.html.haml
- provide(:title, "Collaborators")
.row
  %aside.span4
  .span8
    %h2
      Collaborators for Album: #{@album.title}
      %small= "#{@collaborators.count} invitations"
    - if current_user?(@album.user)
      = link_to "Invite friend", '#', class: "btn btn-large btn-primary"
    %ul.invitations
      = render 'users/collaborators', object: @collaborators

app/views/albums/invitations.html.haml
- provide(:title, "Invitations")
.row
  %aside.span4
  .span8
    %h2
      Invitations for Album: #{@album.title}
      %small= "#{@invited_users.count} invitations"
    - if current_user?(@album.user)
      = link_to "Invite friend", '#', class: "btn btn-large btn-primary"
    %ul.invitations
      = render 'users/invitations', object: @invited_users

app/views/albums/show.html.haml
- provide(:title, @album.title)
.row
  %aside.span4
    %section
      %h1
        = gravatar_for @user
        = @user.name
    %section
      = render 'shared/stats'
  .span8
    %h2
      Album: #{@album.title}
      %small= "#{@album.pictures.count} pictures"
    - if current_user?(@album.user)
      = link_to "Add picture", new_album_picture_path(@album), class: "btn btn-large btn-primary"
    %ul.pictures.thumbnails
      = render @album.pictures