config/routes.rb
Photohub::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :pictures,        only: [:edit, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]

  resources :albums,          only: [:show, :create, :destroy] do
    resources :pictures,        only: [:new, :create]
    member do
      post 'invite/:user_id', action: 'invite',         as: 'invite_to'
      post 'revoke/:user_id', action: 'revoke',         as: 'revoke_from'
      get  'collaborators',   action: 'collaborators',  as: 'collaborators'
      get  'invitations',     action: 'invitations',    as: 'invitations'
    end
  end

  resources :collaborations,  only: [:index] do
    collection do
      get   'pending',  action: 'pending',  as: 'pending'
    end
    member do
      post  'accept',   action: 'accept',   as: 'accept'
      post  'reject',   action: 'reject',   as: 'reject'
    end
  end

  root to: "static_pages#home"

  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  match "/help", to: "static_pages#help"
  match "/contact", to: "static_pages#contact"

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  user_id            :integer
#  album_id           :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Picture < ActiveRecord::Base
  attr_accessible :user_id, :name, :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  belongs_to :album
  belongs_to :user

  validates :album_id, presence: true
  validates :user_id, presence: true
  validates :name, presence: true, allow_blank: false

  validates :image, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :image
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :signed_in_user,  only: [:new, :create, :destroy]
  before_filter :correct_user,    only: [:edit, :update, :destroy]
  before_filter :album_owner,     only: [:new, :create]

  def new
    @picture = Picture.new
  end

  def create
    @picture = @album.pictures.build(params[:picture])
    @picture.user = current_user
    if @picture.save
      flash[:success] = "New picture added: #{@picture.name}"
      redirect_to @album
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @picture.update_attributes(params[:picture])
      flash[:success] = "Name updated!"
      redirect_to @picture.album
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to @picture.album
  end

  private

    def correct_user
      @picture = current_user.pictures.find_by_id!(params[:id])
    rescue
      redirect_to root_url
    end

    def album_owner
      @album = current_user.albums.find_by_id!(params[:album_id])
    rescue
      redirect_to root_url
    end

end

app/views/pictures/_fields.html.haml
= render 'shared/error_messages', object: f.object

= f.label :name
= f.text_field :name

= f.label :image
= f.file_field :image

app/views/pictures/_picture.html.haml
%li.span2
  .thumbnail
    = image_tag picture.image.url(:thumb)
    %h3= link_to picture.name, picture.image.url, class: "content"
    %p.timestamp
      Added #{ time_ago_in_words(picture.created_at) } ago by #{ link_to picture.user.name, user_path(picture.user) }.
    = render 'shared/actions_picture', object: picture

app/views/pictures/edit.html.haml
- provide(:title, 'Edit picture')
%h1= "Editing picture"
.row
  .span6.offset3
    = form_for(@picture) do |f|
      = f.label :name
      = f.text_field :name
      = f.submit "Save", class: "btn btn-large btn-primary"

app/views/pictures/new.html.haml
- provide(:title, 'New Picture')
%h1= "Add a new picture"
.row
  .span6.offset3
    = form_for(@picture, url: album_pictures_path, html: { multipart: true }) do |f|
      = render 'fields', f: f
      = f.submit "Save", class: "btn btn-large btn-primary"