config/routes.rb
Photohub::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :pictures,        only: [:edit, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]

  resources :albums,          only: [:show, :create, :destroy] do
    resources :pictures,        only: [:new, :create]
    member do
      post 'invite/:user_id', action: 'invite',         as: 'invite_to'
      post 'revoke/:user_id', action: 'revoke',         as: 'revoke_from'
      get  'collaborators',   action: 'collaborators',  as: 'collaborators'
      get  'invitations',     action: 'invitations',    as: 'invitations'
    end
  end

  resources :collaborations,  only: [:index] do
    collection do
      get   'pending',  action: 'pending',  as: 'pending'
    end
    member do
      post  'accept',   action: 'accept',   as: 'accept'
      post  'reject',   action: 'reject',   as: 'reject'
    end
  end

  root to: "static_pages#home"

  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  match "/help", to: "static_pages#help"
  match "/contact", to: "static_pages#contact"

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href=>"http://railstutorial.org/"}= "Rails Tutorial"
    by Michael Hartl
  %nav
    %ul
      %li
        %a{:href=>"http://news.railstutorial.org/"}= "News"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "PhotoHub", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home",     root_path
          %li= link_to "Help",     help_path
          %li= link_to "Contact",  contact_path
          - if signed_in?
            %li= link_to "Users",  users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
%script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}
<![endif]-->

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'

  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?